package in.rk.service.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-05-14T17:09:34.889+05:30
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.rk.in/service/Calculator/", name = "Calculator")
@XmlSeeAlso({in.rk.schema.calculator.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Calculator {

    @WebMethod(operationName = "AddOrMultiply", action = "http://www.rk.in/service/Calculator/AddOrMultiply")
    @WebResult(name = "calculateDataResponse", targetNamespace = "http://www.rk.in/schema/Calculator", partName = "calculateDataResponse")
    public in.rk.schema.calculator.CalculateDataResponse addOrMultiply(

        @WebParam(partName = "calculateDataRequest", name = "calculateDataRequest", targetNamespace = "http://www.rk.in/schema/Calculator")
        in.rk.schema.calculator.CalculateDataRequest calculateDataRequest
    );
}
