package com.rk.web.soap.apache.cxf.codegen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-06T17:19:54.752+05:30
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.rk.com/service/Calculator/", name = "Calculator")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Calculator {

    @WebMethod(operationName = "AddOrMultiply", action = "http://www.rk.com/service/Calculator/AddOrMultiply")
    @WebResult(name = "calculateDataResponse", targetNamespace = "http://www.rk.com/schema/Calculator", partName = "calculateDataResponse")
    public CalculateDataResponse addOrMultiply(

        @WebParam(partName = "calculateDataRequest", name = "calculateDataRequest", targetNamespace = "http://www.rk.com/schema/Calculator")
        CalculateDataRequest calculateDataRequest
    );
}
