spring:
   application:
      name: demoservice
server:
   port: 8080

# management part is for actuator
#management:
#   security:
#      enabled: false
#   port: 9000


management:
   endpoints:
      web:
         exposure:
            include: "*" 

# actual info
info:
   team:
      name: RK
      dev: rkdev
   version: 1.0
   project:
      owner: RK Learning
      
cxf:
   path: /Service
