package org.rk.service.calculator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-06T17:07:04.950+05:30
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "Calculator",
                  wsdlLocation = "file:/C:/git/webservices/webjavasoapapachecxf/src/main/resources/wsdl/Calculator.wsdl",
                  targetNamespace = "http://www.rk.org/service/Calculator/")
public class Calculator_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.rk.org/service/Calculator/", "Calculator");
    public final static QName CalculatorSOAP = new QName("http://www.rk.org/service/Calculator/", "CalculatorSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/git/webservices/webjavasoapapachecxf/src/main/resources/wsdl/Calculator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Calculator_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/git/webservices/webjavasoapapachecxf/src/main/resources/wsdl/Calculator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Calculator_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Calculator_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Calculator_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Calculator_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Calculator_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Calculator_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Calculator
     */
    @WebEndpoint(name = "CalculatorSOAP")
    public Calculator getCalculatorSOAP() {
        return super.getPort(CalculatorSOAP, Calculator.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculator
     */
    @WebEndpoint(name = "CalculatorSOAP")
    public Calculator getCalculatorSOAP(WebServiceFeature... features) {
        return super.getPort(CalculatorSOAP, Calculator.class, features);
    }

}
